name: Deploy Web Project

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.branch }}

      - name: Install Dependencies
        working-directory: .
        run: npm install
        
      - name: Ensure Config Directory Exists
        run: mkdir -p ./src/config

      - name: Log Config Secret
        run: |
          cat {{ github.event.client_payload.config_secret }}

      - name: Set Config Json File
        id: create-json 
        uses: jsdaniell/create-json@v1.2.2 
        with:
          name: "config.json" 
          json: ${{ github.event.client_payload.config_secret }}
          dir: './src/config' 

      - name: Build Project
        working-directory: .
        run: npm run build

      - name: Create Destination Directory If Not Exists
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p ${{ github.event.client_payload.destination_directory }}"

      - name: Deploy Files to Server
        run: |
          rsync -avz -e "ssh -i ${{ secrets.SERVER_SSH_KEY }}" \
          ./${{ github.event.client_payload.source_directory }}/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ github.event.client_payload.destination_directory }}
