name: Deploy Web Project

on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      source_directory:
        required: true
        type: string
      destination_directory:
        required: true
        type: string
    secrets:
      SERVER_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          echo "Running build command: ${{ inputs.build_command }}"
          eval "${{ inputs.build_command }}"

      - name: Create Destination Directory If Not Exists
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "Creating destination directory if it doesn't exist: ${{ inputs.destination_directory }}"
          ssh -i ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ inputs.destination_directory }}"

      - name: Deploy Files to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "Deploying files from ${{ inputs.source_directory }} to ${{ inputs.destination_directory }}"
          rsync -avz -e "ssh -i $${{ secrets.SERVER_SSH_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ inputs.destination_directory }}
