name: Deploy Web Project

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          ref: ${{ github.event.client_payload.branch }}

      - name: Install Dependencies
        run: npm install

      - name: Decode Config Secret
        id: decode-config
        run: |
          echo "${{ github.event.client_payload.config_secret }}" | base64 --decode > ./src/lib/axios/config.json
          cat ./src/lib/axios/config.json  # 파일 내용을 출력해 확인
      - name: Build Project
        run: npm run build

      - name: Create Destination Directory If Not Exists
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "mkdir -p ${{ github.event.client_payload.destination_directory }}"

      - name: Deploy Files to Server
        run: |
          rsync -avz -e "ssh -i ${{ secrets.SERVER_SSH_KEY }}" \
          ./${{ github.event.client_payload.source_directory }}/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ github.event.client_payload.destination_directory }}
